HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory nomatch hist_ignore_all_dups hist_ignore_space
unsetopt autocd

autoload -Uz compinit
autoload -U colors && colors
compinit

# export DESKTOP_ROOT=$(dirname $(dirname $(readlink ~/.zshrc)))
export DESKTOP_ROOT="/Users/$(whoami)/$(dirname $(dirname $(readlink ~/.zshrc)))"

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias vi='vim'

# suffix alias
alias -s rb=vim
alias -s log="less -MN"
alias -s html=safari

bindkey -e

# X terminal keys
bindkey '^[[1;5D' vi-backward-word
bindkey '^[[1;5C' vi-forward-word
bindkey '^[OF' vi-end-of-line
bindkey '^[OH' vi-beginning-of-line
bindkey '^[[3~' delete-char
bindkey '^[[3;5~' delete-word

# Non-X terminal keys, where different
bindkey '^[[D' vi-backward-word
bindkey '^[[C' vi-forward-word
bindkey '^[[4~' vi-end-of-line
bindkey '^[[1~' vi-beginning-of-line

source $DESKTOP_ROOT/vendor/zgen/zgen.zsh

source ~/.caquino_tools.zsh

#chruby
  [[ -s $(brew --prefix)/opt/chruby/share/chruby/chruby.sh ]] && . $(brew --prefix)/opt/chruby/share/chruby/chruby.sh
  [[ -s $(brew --prefix)/opt/chruby/share/chruby/auto.sh ]] && . $(brew --prefix)/opt/chruby/share/chruby/auto.sh

#autojump
  [[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

function prompt_time {
    echo \[$(date +%T)\]
}
RPROMPT='$(prompt_time)'

# global /etc/zshprofile overrides $PATH
# oh-my-zsh overrides $PAGER
source $HOME/.zshenv

# added by travis gem
# HUH? where did this come from...
# [ -f /Users/brann/.travis/travis.sh ] && source /Users/brann/.travis/travis.sh

# ADDED BY DOCKER-IMAGES
source /Users/brann/Code/zendesk/docker-images/dockmaster/zdi.sh

NEWLINE=$'\n'
PROMPT="$PROMPT${NEWLINE} $ "
DISABLE_VENV_CD=1
DISABLE_UPDATE_PROMPT=true
if ! zgen saved; then
    echo 'Creating a zgen save'

    zgen oh-my-zsh

    zgen oh-my-zsh plugins/git

    zgen oh-my-zsh plugins/virtualenvwrapper

    zgen oh-my-zsh plugins/chruby

    zgen load zsh-users/zsh-syntax-highlighting

    zgen oh-my-zsh themes/agnoster

    zgen save
fi
