HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory nomatch hist_ignore_all_dups hist_ignore_space
unsetopt autocd

autoload -Uz compinit
compinit

autoload -Uz promptinit
promptinit

# global /etc/zshprofile overrides $PATH
. $HOME/.zshenv
export EDITOR=vim
export PAGER='less -R'

# source $(dirname $(dirname $(readlink $0)))/antigen/antigen.zsh
. ~/projects/desktop/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle git

antigen bundle zsh-users/zsh-syntax-highlighting

antigen theme jreese

antigen apply

alias ls='ls --color=auto'
alias grep='grep --color=auto'

bindkey -e

# X terminal keys
bindkey '^[[1;5D' vi-backward-word
bindkey '^[[1;5C' vi-forward-word
bindkey '^[OF' vi-end-of-line
bindkey '^[OH' vi-beginning-of-line
bindkey '^[[3~' delete-char
bindkey '^[[3;5~' delete-word

# Non-X terminal keys, where different
bindkey '^[[D' vi-backward-word
bindkey '^[[C' vi-forward-word
bindkey '^[[4~' vi-end-of-line
bindkey '^[[1~' vi-beginning-of-line

source /usr/share/autojump/autojump.zsh
