flags: {}
packages: []
extra-deps:
- gtk-traymanager-0.1.5
- optparse-declarative-0.3.0
- webkit-0.14.1.0
- X11-xft-0.3.1
- xdg-basedir-0.2.2
- xmonad-0.11.1
- xmonad-contrib-0.11.4
resolver: lts-3.4
